# Generated by Django 3.1.4 on 2020-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.CharField(max_length=10000)),
                ('analytics', models.CharField(max_length=10000)),
                ('third_party', models.CharField(max_length=10000)),
                ('ads', models.CharField(max_length=10000)),
                ('children_pp', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'privacy policy',
            },
        ),
    ]
